import 'package:flutter/material.dart';
import '../models/course_model.dart';

class CourseProvider extends ChangeNotifier {
  final List<CourseModel> _courses = const [
    CourseModel(
      id: 'course_01',
      title: 'AIAPGET 2026 Complete Preparation',
      instructorName: 'Dr. Aditya Sharma (AIR 3)',
      badge: CourseBadge.bestseller,
      category: 'PG Entrance',
      rating: 4.9,
      duration: '12 Months',
      studentCount: 1420,
      price: 12999,
      oldPrice: 19999,
      gradientColors: [Color(0xFFECFDF5), Color(0xFFD1FAE5)],
    ),
    CourseModel(
      id: 'course_02',
      title: 'NEET PG Homeopathy Foundation',
      instructorName: 'Dr. Rajesh Patel (PhD)',
      badge: CourseBadge.newBadge,
      category: 'Foundation',
      rating: 4.7,
      duration: '9 Months',
      studentCount: 850,
      price: 9999,
      oldPrice: 14999,
      gradientColors: [Color(0xFFF0FDF4), Color(0xFFDCFCE7)],
    ),
    CourseModel(
      id: 'course_03',
      title: 'Organon of Medicine Deep Dive',
      instructorName: 'Dr. Priya Ramachandran',
      badge: CourseBadge.trending,
      category: 'Organon',
      rating: 4.8,
      duration: '6 Months',
      studentCount: 980,
      price: 4999,
      oldPrice: 7999,
      gradientColors: [Color(0xFFE8F5E9), Color(0xFFA5D6A7)],
    ),
    CourseModel(
      id: 'course_04',
      title: 'Materia Medica Masterclass',
      instructorName: 'Dr. Vivek Kumar (MD)',
      badge: CourseBadge.popular,
      category: 'Materia Medica',
      rating: 4.9,
      duration: '8 Months',
      studentCount: 1450,
      price: 5999,
      oldPrice: 8999,
      gradientColors: [Color(0xFFE6F4EA), Color(0xFFB7E1CD)],
    ),
    CourseModel(
      id: 'course_05',
      title: 'Homeopathic Pharmacy',
      instructorName: 'Dr. Neha Shah',
      badge: CourseBadge.featured,
      category: 'Pharmacy',
      rating: 4.6,
      duration: '4 Months',
      studentCount: 510,
      price: 3999,
      oldPrice: 5999,
      gradientColors: [Color(0xFFF0FDFC), Color(0xFFCCFBF1)],
    ),
    CourseModel(
      id: 'course_06',
      title: 'Clinical Case Discussions',
      instructorName: 'Dr. Sanjay Sen',
      badge: CourseBadge.bestseller,
      category: 'Clinical',
      rating: 4.9,
      duration: '5 Months',
      studentCount: 1120,
      price: 2999,
      oldPrice: 4999,
      gradientColors: [Color(0xFFECFDF5), Color(0xFFA7F3D0)],
    ),
    CourseModel(
      id: 'course_07',
      title: 'Anatomy for BHMS',
      instructorName: 'Dr. Amit Trivedi',
      badge: CourseBadge.newBadge,
      category: 'Anatomy',
      rating: 4.5,
      duration: '7 Months',
      studentCount: 670,
      price: 3499,
      oldPrice: 5499,
      gradientColors: [Color(0xFFF4FBF7), Color(0xFFD1EBE1)],
    ),
    CourseModel(
      id: 'course_08',
      title: 'Physiology Essentials',
      instructorName: 'Dr. Shalini Gupta',
      badge: CourseBadge.trending,
      category: 'Physiology',
      rating: 4.6,
      duration: '6 Months',
      studentCount: 720,
      price: 3499,
      oldPrice: 5499,
      gradientColors: [Color(0xFFE6F7F0), Color(0xFFC7EEDC)],
    ),
    CourseModel(
      id: 'course_09',
      title: 'Pathology Revision',
      instructorName: 'Dr. Suresh Mehta',
      badge: CourseBadge.popular,
      category: 'Pathology',
      rating: 4.7,
      duration: '3 Months',
      studentCount: 890,
      price: 2499,
      oldPrice: 3999,
      gradientColors: [Color(0xFFEAFAF1), Color(0xFFD5F5E3)],
    ),
    CourseModel(
      id: 'course_10',
      title: 'Repertory Crash Course',
      instructorName: 'Dr. Kiran Patel',
      badge: CourseBadge.featured,
      category: 'Repertory',
      rating: 4.8,
      duration: '2 Months',
      studentCount: 640,
      price: 1999,
      oldPrice: 2999,
      gradientColors: [Color(0xFFE0F2F1), Color(0xFFB2DFDB)],
    ),
    CourseModel(
      id: 'course_11',
      title: 'Research Methodology',
      instructorName: 'Dr. Ananya Roy',
      badge: CourseBadge.newBadge,
      category: 'Research',
      rating: 4.4,
      duration: '3 Months',
      studentCount: 430,
      price: 1499,
      oldPrice: 2499,
      gradientColors: [Color(0xFFF1F8E9), Color(0xFFDCEDC8)],
    ),
    CourseModel(
      id: 'course_12',
      title: 'Internship Clinical Program',
      instructorName: 'Dr. Vikram Sethi',
      badge: CourseBadge.bestseller,
      category: 'Internship',
      rating: 4.9,
      duration: '10 Months',
      studentCount: 1580,
      price: 7999,
      oldPrice: 11999,
      gradientColors: [Color(0xFFECFDF5), Color(0xFFB9F6CA)],
    ),
  ];

  List<CourseModel> get courses => _courses;

  final Set<String> _enrolledCourseIds = {};

  bool isEnrolled(String courseId) => _enrolledCourseIds.contains(courseId);

  void enrollCourse(String courseId) {
    if (!_enrolledCourseIds.contains(courseId)) {
      _enrolledCourseIds.add(courseId);
      notifyListeners();
    }
  }
}
