import '../models/student_model.dart';

class AppConstants {
  static const List<String> courses = [
    'Homeopathy Foundation',
    'Advanced Prescribing',
    'Chronic Cases Study',
    'Organon of Medicine',
    'Materia Medica Masterclass',
  ];

  static const List<String> subscriptions = [
    'Basic',
    'Premium',
    'VIP',
    'Trial',
  ];

  static const List<String> statuses = [
    'Active',
    'Inactive',
    'Trial',
    'Expired',
  ];

  static const List<int> paginationOptions = [10, 25, 50, 100];

  static List<StudentModel> getSeedStudents() {
    return [
      StudentModel(
        id: '1',
        name: 'Dr. Albert Allen',
        email: 'albert.allen@example.com',
        phone: '+1 (555) 019-2834',
        course: 'Homeopathy Foundation',
        subscription: 'Premium',
        status: 'Active',
        joinedDate: DateTime(2025, 10, 12),
      ),
      StudentModel(
        id: '2',
        name: 'Dr. Clara Bow',
        email: 'clara.bow@example.com',
        phone: '+1 (555) 021-9876',
        course: 'Advanced Prescribing',
        subscription: 'VIP',
        status: 'Active',
        joinedDate: DateTime(2025, 11, 01),
      ),
      StudentModel(
        id: '3',
        name: 'Dr. David Miller',
        email: 'david.miller@example.com',
        phone: '+1 (555) 022-3456',
        course: 'Chronic Cases Study',
        subscription: 'Basic',
        status: 'Inactive',
        joinedDate: DateTime(2025, 08, 15),
      ),
      StudentModel(
        id: '4',
        name: 'Dr. Emma Watson',
        email: 'emma.watson@example.com',
        phone: '+1 (555) 023-4567',
        course: 'Organon of Medicine',
        subscription: 'Trial',
        status: 'Trial',
        joinedDate: DateTime(2026, 01, 10),
      ),
      StudentModel(
        id: '5',
        name: 'Dr. Frank Sinatra',
        email: 'frank.sinatra@example.com',
        phone: '+1 (555) 024-5678',
        course: 'Materia Medica Masterclass',
        subscription: 'Basic',
        status: 'Expired',
        joinedDate: DateTime(2025, 05, 20),
      ),
      StudentModel(
        id: '6',
        name: 'Dr. Grace Hopper',
        email: 'grace.hopper@example.com',
        phone: '+1 (555) 025-6789',
        course: 'Homeopathy Foundation',
        subscription: 'VIP',
        status: 'Active',
        joinedDate: DateTime(2025, 09, 05),
      ),
      StudentModel(
        id: '7',
        name: 'Dr. Henry Cavill',
        email: 'henry.cavill@example.com',
        phone: '+1 (555) 026-7890',
        course: 'Advanced Prescribing',
        subscription: 'Premium',
        status: 'Active',
        joinedDate: DateTime(2025, 12, 18),
      ),
      StudentModel(
        id: '8',
        name: 'Dr. Irene Adler',
        email: 'irene.adler@example.com',
        phone: '+1 (555) 027-8901',
        course: 'Chronic Cases Study',
        subscription: 'Trial',
        status: 'Trial',
        joinedDate: DateTime(2026, 01, 20),
      ),
      StudentModel(
        id: '9',
        name: 'Dr. Jack Ryan',
        email: 'jack.ryan@example.com',
        phone: '+1 (555) 028-9012',
        course: 'Organon of Medicine',
        subscription: 'Basic',
        status: 'Inactive',
        joinedDate: DateTime(2025, 07, 11),
      ),
      StudentModel(
        id: '10',
        name: 'Dr. Kate Austen',
        email: 'kate.austen@example.com',
        phone: '+1 (555) 029-0123',
        course: 'Materia Medica Masterclass',
        subscription: 'Premium',
        status: 'Active',
        joinedDate: DateTime(2025, 10, 29),
      ),
      StudentModel(
        id: '11',
        name: 'Dr. Leo Fitz',
        email: 'leo.fitz@example.com',
        phone: '+1 (555) 030-1234',
        course: 'Homeopathy Foundation',
        subscription: 'Basic',
        status: 'Expired',
        joinedDate: DateTime(2025, 04, 14),
      ),
      StudentModel(
        id: '12',
        name: 'Dr. Melinda May',
        email: 'melinda.may@example.com',
        phone: '+1 (555) 031-2345',
        course: 'Advanced Prescribing',
        subscription: 'VIP',
        status: 'Active',
        joinedDate: DateTime(2025, 11, 15),
      ),
      StudentModel(
        id: '13',
        name: 'Dr. Ned Stark',
        email: 'ned.stark@example.com',
        phone: '+1 (555) 032-3456',
        course: 'Chronic Cases Study',
        subscription: 'Premium',
        status: 'Inactive',
        joinedDate: DateTime(2025, 06, 02),
      ),
      StudentModel(
        id: '14',
        name: 'Dr. Olivia Dunham',
        email: 'olivia.dunham@example.com',
        phone: '+1 (555) 033-4567',
        course: 'Organon of Medicine',
        subscription: 'Premium',
        status: 'Active',
        joinedDate: DateTime(2025, 09, 22),
      ),
      StudentModel(
        id: '15',
        name: 'Dr. Peter Parker',
        email: 'peter.parker@example.com',
        phone: '+1 (555) 034-5678',
        course: 'Materia Medica Masterclass',
        subscription: 'Trial',
        status: 'Trial',
        joinedDate: DateTime(2026, 02, 01),
      ),
      StudentModel(
        id: '16',
        name: 'Dr. Quint Vance',
        email: 'quint.vance@example.com',
        phone: '+1 (555) 035-6789',
        course: 'Homeopathy Foundation',
        subscription: 'Basic',
        status: 'Active',
        joinedDate: DateTime(2025, 08, 30),
      ),
      StudentModel(
        id: '17',
        name: 'Dr. Rose Tyler',
        email: 'rose.tyler@example.com',
        phone: '+1 (555) 036-7890',
        course: 'Advanced Prescribing',
        subscription: 'VIP',
        status: 'Active',
        joinedDate: DateTime(2025, 10, 05),
      ),
      StudentModel(
        id: '18',
        name: 'Dr. Sam Wilson',
        email: 'sam.wilson@example.com',
        phone: '+1 (555) 037-8901',
        course: 'Chronic Cases Study',
        subscription: 'Basic',
        status: 'Expired',
        joinedDate: DateTime(2025, 03, 12),
      ),
      StudentModel(
        id: '19',
        name: 'Dr. Tony Stark',
        email: 'tony.stark@example.com',
        phone: '+1 (555) 038-9012',
        course: 'Organon of Medicine',
        subscription: 'VIP',
        status: 'Active',
        joinedDate: DateTime(2025, 07, 04),
      ),
      StudentModel(
        id: '20',
        name: 'Dr. Ursula Buffay',
        email: 'ursula.buffay@example.com',
        phone: '+1 (555) 039-0123',
        course: 'Materia Medica Masterclass',
        subscription: 'Premium',
        status: 'Inactive',
        joinedDate: DateTime(2025, 05, 14),
      ),
    ];
  }
}
