import 'package:homeopathy/admin/screens/question_bank/widget/model/question_model.dart';

final List<Question> dummyQuestions = [
  Question(
    id: "Q-10241",
    question: "A 58-year-old man presents with acute chest pain radiating to his left arm. What is the most appropriate next pharmacological step?",
    course: "MBBS Final Year",
    subject: "Medicine",
    module: "Cardiology",
    difficulty: "Hard",
    status: "Active",
    chapter: "Chapter 4",
    topic: "Myocardial Infarction",
    type: "MCQ",
  ),
  Question(
    id: "Q-10242",
    question: "Which of the following ECG changes is most characteristic of acute pericarditis?",
    course: "MBBS Final Year",
    subject: "Medicine",
    module: "Cardiology",
    difficulty: "Medium",
    status: "Active",
    chapter: "Chapter 3",
    topic: "Pericarditis",
    type: "MCQ",
  ),
  Question(
    id: "Q-10243",
    question: "Select all drugs that are contraindicated in patients with myasthenia gravis.",
    course: "MBBS Final Year",
    subject: "Medicine",
    module: "Neurology",
    difficulty: "Hard",
    status: "Active",
    chapter: "Chapter 8",
    topic: "Myasthenia",
    type: "Multiple Select",
  ),
  Question(
    id: "Q-10244",
    question: "A 45-year-old female presents with sudden onset of severe headache, described as the worst headache of her life.",
    course: "MBBS Final Year",
    subject: "Medicine",
    module: "Neurology",
    difficulty: "Hard",
    status: "Active",
    chapter: "Chapter 6",
    topic: "Stroke",
    type: "MCQ",
  ),
  Question(
    id: "Q-10245",
    question: "True or False: Symphytum officinale is primary remedy for accelerating union of fractured bones.",
    course: "MBBS Final Year",
    subject: "Surgery",
    module: "Orthopaedics",
    difficulty: "Easy",
    status: "Active",
    chapter: "Chapter 10",
    topic: "Fractures",
    type: "True/False",
  ),
  Question(
    id: "Q-10246",
    question: "A patient presents with sharp, stitching pain in the chest, worse from any movement. Which homeopathic remedy is indicated?",
    course: "MBBS Final Year",
    subject: "Medicine",
    module: "Cardiology",
    difficulty: "Easy",
    status: "Draft",
    chapter: "Chapter 5",
    topic: "Bryonia",
    type: "MCQ",
  ),
  Question(
    id: "Q-10247",
    question: "Explain the initial nursing management protocol for hypovolemic shock in post-operative patients.",
    course: "Nursing (BSc)",
    subject: "Medicine",
    module: "Cardiology",
    difficulty: "Medium",
    status: "Active",
    chapter: "Chapter 2",
    topic: "Resuscitation",
    type: "MCQ",
  ),
  Question(
    id: "Q-10248",
    question: "Which cranial nerve is primarily affected in a patient presenting with Bell's palsy?",
    course: "Nursing (BSc)",
    subject: "Medicine",
    module: "Neurology",
    difficulty: "Easy",
    status: "Active",
    chapter: "Chapter 7",
    topic: "Palsy",
    type: "MCQ",
  ),
  Question(
    id: "Q-10249",
    question: "Which of the following is the most common cause of high fever with delirium in pediatric patients?",
    course: "NEET PG",
    subject: "Medicine",
    module: "Neurology",
    difficulty: "Medium",
    status: "Draft",
    chapter: "Chapter 1",
    topic: "Pediatrics",
    type: "MCQ",
  ),
  Question(
    id: "Q-10250",
    question: "Select the most appropriate remedy for post-extraction neuralgic dental pain which is worse from cold air.",
    course: "NEET PG",
    subject: "Surgery",
    module: "ENT",
    difficulty: "Hard",
    status: "Active",
    chapter: "Chapter 9",
    topic: "Post-Op",
    type: "MCQ",
  ),
];
